### ISSUE TITLE
plugin generates directories on macosx with "\" as part of directory name

### ISSUE THREAD

**Issue by fortunecookiezen** [charotAmine/azureBlueprintsExtension#1]
Generation of workspaces or artifacts results in backslash characters in resource names on macos.

![Screen Shot 2019-10-14 at 10 52 05 AM](https://user-images.githubusercontent.com/11577636/66765064-b90e9800-ee70-11e9-93e1-c2f74f8363fe.png)

If plugin is windows-only, I didn't see any indication of that anywhere.

**Comment by charotAmine** [comment]
Thanks for the feedback. I will try to fix it asap. Thanks

**Comment by charotAmine** [comment]
The issue has been resolved. Thank you for your feedback
